name: masterdata
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - black
  - mypy
  - igraph
  - requests
prefix:
  - /Users/alcastrica/miniforge3/envs/masterdata