name: master-data-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-build
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - black
  - mypy
  - igraph
  - requests
  - nltk
  - pytest